scs-credhub:
  url: https://10.244.0.144:8844
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIE5TCCA02gAwIBAgIRAJAii9CXiWUwMGT0vgHyUuQwDQYJKoZIhvcNAQELBQAw
    UTEMMAoGA1UEBhMDVVNBMRYwFAYDVQQKEw1DbG91ZCBGb3VuZHJ5MSkwJwYDVQQD
    EyBTcHJpbmcgQ2xvdWQgU2VydmljZXMgQ3JlZEh1YiBDQTAeFw0xOTAxMjMxOTIw
    MDhaFw0yMDAxMjMxOTIwMDhaME4xDDAKBgNVBAYTA1VTQTEWMBQGA1UEChMNQ2xv
    dWQgRm91bmRyeTEmMCQGA1UEAxMdc3ByaW5nLWNsb3VkLXNlcnZpY2VzLWNyZWRo
    dWIwggGiMA0GCSqGSIb3DQEBAQUAA4IBjwAwggGKAoIBgQDk9W0XEs3k7Qmcd6x+
    XhdRqugI0nv2k66SgnL0WO/jxuoMqIuIjafwPkTgzcJLx8yZz8Di0obhIx/i8VnK
    a8RSZPWH32w+Sn8fe895YUOYYeMyWnQF4dEBV3j/yhJEdMSxnVRpNwx/hCEBeAnT
    gzAmYDrGq3/Wg7b6WlZtSe4zC5P+mWqeqfs5lY48q9oSbbDUe9oTSdMRJK45j1pi
    +L6lXNb+POKq+9ltY2vjSIV+Scsd8E2YYoniAwy1eEtjmLd1Fje7cCeEWkT9ZMRs
    DF8Hbe5Wi2RueMaM4+Jbp0BgwTEJjzMRLFjWEUjlTjBdGbZi9aYiBf9oWP0ODfs1
    6JzO8BT56+dK4c9swjKbbfGcDWke/jSqa4nVd15/vofAX4EolkwlaJQshoYTMha8
    vG0YkKyV7N09tEFDkh4118ivi6facB15sEH+DJod0vxrGXHmKUIJcjYHUvmnFfZ0
    SWI9gGhk6kEk0elQl3UvYhtBIXlG1Rd5Dw4mD9u5OASPxvsCAwEAAaOBujCBtzAO
    BgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYDVR0TAQH/BAIw
    ADAdBgNVHQ4EFgQU/Lro/ZonV7T+g8Z1/C+fsc+4VAQwHwYDVR0jBBgwFoAURvjY
    +g1mIONBMINSok1VD6aBAdIwQgYDVR0RBDswOYIxc3ByaW5nLWNsb3VkLXNlcnZp
    Y2VzLWNyZWRodWIuc2VydmljZS5jZi5pbnRlcm5hbIcEfwAAATANBgkqhkiG9w0B
    AQsFAAOCAYEACKI8fyIsAmggp1jAnXYWfLbpwAKHaELknGGCdhCfBGahH1xhIo5Z
    4OmKElw93kcVGVfcLD3JI+JL3hjJ0GQJq1MXqbGpqRZbNOiJiqfSNxxfoxIfyjbr
    iPPA5GJVRJqZ+mH1NNqdIyVDX7Q7MgIcuy0K5IgRmIRtJCcLCCS+XD89c+UG8Qq9
    kaJmZqQbzSrAY1KuyV7BH4OIuH1ktEFMIFS0yqJfcPpTP0HH9sS5Kt3nB0TCyF8/
    Fna5l9WIBsqVnacVvSNOboBjOVQDIUz1nH3tdxTj3XjOnAz6scJXP6a+RR7Pvnds
    wLKscp/yiIEQ3jWfCKCvYSYw4XK6XWRPtC8a//sIZn4pdqp5aoFkvA2OgudYEhxu
    AnwmT5FMx7ciOe4rC+vAsbQS3Tn3NaFUndAaR4oqnlaIsoV4dpv7/gB7LSJgeFnb
    c/7rAu+iIjX46wDJt9s8E+rp4nLEVtsn+vSd18ecGoLgIF8YoM9ddmy8fQ/LHH/g
    6R5+bEX+1CHX
    -----END CERTIFICATE-----
issuer:
  ca: |
     -----BEGIN CERTIFICATE-----
     MIIEmjCCAwKgAwIBAgIRAO7h3DQfVhoENHNUmqXWiGYwDQYJKoZIhvcNAQELBQAw
     VjEMMAoGA1UEBhMDVVNBMRYwFAYDVQQKEw1DbG91ZCBGb3VuZHJ5MS4wLAYDVQQD
     EyVTcHJpbmcgQ2xvdWQgU2VydmljZXMgQ3JlZGh1YiBtVExTIENBMB4XDTE5MDEy
     NjAwMzEwM1oXDTIwMDEyNjAwMzEwM1owVjEMMAoGA1UEBhMDVVNBMRYwFAYDVQQK
     Ew1DbG91ZCBGb3VuZHJ5MS4wLAYDVQQDEyVTcHJpbmcgQ2xvdWQgU2VydmljZXMg
     Q3JlZGh1YiBtVExTIENBMIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEA
     mRPbAtuauATgormjdCd5gEWPj4nhxSpkkwTYpWR3OyoKsdI5Gm/a7ejHg/X0anA7
     BrCKvu7XAamhD3JJliy/zaSAM2MD8JsOhc3DoVVEZ1sZOCjgQHNdYqWUBqLZdO5x
     j79J+NTRg1T0dLH0N9faHLm2S7a/9krIUGxCdUX2R1i/3FxUI6dEoxiWxadhP4Jt
     VuVkApWO1sE4gMW6qGQWbDF7HzmhF1UeFkzqfLRFhTt4GO5iYnR33px/zvuKt6FN
     OD7PN2kUbcApjGjHrygMoBV148Ovi/WN0KhoEcmo1nw5lREwPd03onQXWZe4K1I7
     yCV0d9pX9XDxeqIEDIlwOvCjDy9x3GciEj/s2IFRvO5NwrgECap18t6nTbELNIho
     am8RT0WJYCeQqmH2vjp/SrexXwEvA4kPIssIp3j1CTc/J/vq+uxNCCPXctD0/Wpi
     +JZ6zzGcmw6GRQ1kZtIv/dSNjdo5w8CuLu4VW0w4eVE5rzdPoLjtzeA0bNyXFeq5
     AgMBAAGjYzBhMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1Ud
     DgQWBBT5kcNzF6qQd9NFMrGTA4xB9pu5kjAfBgNVHSMEGDAWgBT5kcNzF6qQd9NF
     MrGTA4xB9pu5kjANBgkqhkiG9w0BAQsFAAOCAYEAG43Nm5iu4PiqqAJbkcKyNsyx
     uyXthixWF56QFjh+KtHLu5Bo4fGZz32fYVtmmxjGv0Tv9JdydZPcExo4g31H6JEh
     SzjNFrWwdHw4AHubjsiyQ5OBK9UEpa2wnekRcW+7/uBtBVeEGt+Tq7b/dm9Hvfph
     7fW303aXN/Neqf5vlDp8jLS6WbUILAeWkAHvlJunGDyvSS9w+Qk3MB0B4CVK98G1
     VVNQbgnvq2UjaU52rJ3irk7gTq6Z9W8C2M//C9YqOh67rnFoJA57yzNpL6CYx2JL
     XEHHyqolDmtadIZiCtPXba9Mhnc/KtGcf4XShpNBru3Pe0oDe5mp57OqJtuueefB
     QMlnP890jKQq2v2tI5okPsXzbxnOLLOiYnsv4mUEFzHg5fmEmS3M6Do6o7wNOmJZ
     6wC8Y2tMWXyKUrvpNSJHb48Xn3GNC3gpEMGltwA7QwfD8BozF2/Q++POhWbFILrx
     1Dj3vHS+lqCSTughMmbgu7xf3o/Rn6LPDRYmTMEO
     -----END CERTIFICATE-----
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIEsjCCAxqgAwIBAgIQOSu/gqnZXuLfzp2LORuY7jANBgkqhkiG9w0BAQsFADBW
    MQwwCgYDVQQGEwNVU0ExFjAUBgNVBAoTDUNsb3VkIEZvdW5kcnkxLjAsBgNVBAMT
    JVNwcmluZyBDbG91ZCBTZXJ2aWNlcyBDcmVkaHViIG1UTFMgQ0EwHhcNMTkwMTI4
    MjMyMzQwWhcNMjAwMTI4MjMyMzQwWjBvMQwwCgYDVQQGEwNVU0ExFjAUBgNVBAoT
    DUNsb3VkIEZvdW5kcnkxRzBFBgNVBAMTPlNwcmluZyBDbG91ZCBDb25maWcgU2Vy
    dmVyIGJyb2tlciBDcmVkaHViIGludGVybWVkaWF0ZSBtVExTIENBMIIBojANBgkq
    hkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAnKNJWuTJJJa5pW6P8/RmJw6SSaSQn4wf
    sSNw4s0AhAQ3FVVoirRK61TpqO0Msb5veopF7JW8pjpOgWwLpRFen6N69gbDQTY+
    t3fpz38o5uMHvmuLEMosMHnzvpqWJ6rXKghiDNtxs3LP9WZBL50D/tU/lGUEFerp
    DjrrFkfiWP2AWxoXZ1o+2RQ46NW6koQBx9vV6FiIp//R/xc24yMmB3wW6vXjYgxh
    DocEXG+34oIExB0ZN9sCKEPg3thXDh93dOXiFwuWvPwcO8qG0pKZeU61IAkENCVG
    eCC7NzI3WZQuC6kh0oszJtwv1jT/pi056L49wD9yyv1Sh0Ca2UK6vkbHglutOTto
    M1Zj8t2tJnALjXRtm0bbZJtX6IcwITBI/vX1CsC2I+M5Q8FOQOj25PAdH/IXeunp
    WsHl/r+v9hCcVWaGGkBcvJm5A1gslz1Lmyil2lI/xA6f2Bbt+M0B6MzwwPOizrl2
    BSLuMRmnIoK1b5KysId9Zpdo7LbHCF7xAgMBAAGjYzBhMA4GA1UdDwEB/wQEAwIB
    BjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRytw0BSDpKVrJyLCDNLRj2L8WY
    bzAfBgNVHSMEGDAWgBT5kcNzF6qQd9NFMrGTA4xB9pu5kjANBgkqhkiG9w0BAQsF
    AAOCAYEAbUk0PXYfUG/mtdPuzmXSt1zIhPr+2Zft1IxziKto0fL2BP1mRoOxrV5v
    brqgzqAwBKnVaGkBexlEXfVJYDHChU14OiMPLjkPe6CPabi7cRfTSiCZUy9YpSnE
    OH3rNxtGkDmqCs1ozqjoAkewHXc8Vm1YQd+ZHt27gt0Q7vhspMD2uBF/B1mvCR8q
    kj2H0mwyD3DfIu1jNNhfiG6HaA0S1ldwz1r6F6Atk+IefDjAf68pufgZk8gFcSiC
    iCWIC7gBTVlLVfkSLyzEIIpLRecUaffUVqU0tpTma/Ipk3Lz1O+gFne0l6y/MSVg
    objnQuhWgLv66XTna4Onfw2bpJ1Vi5CpNL7UWEE8vrGF3CcZm1d29/9Tha1Felkj
    W2my0Gw4LjfoLfDcHEYazz8TZlGLjFExXe7IPpvHE89WT5ndtAT5o1nZw50iLvv7
    DY9ZMHQDgHd5i4xJ6T4GtnhiMXrxMdW9yhO5J3xKbqqxapGutK7IWdZzIT8VsQcu
    nXsjSTQ6
    -----END CERTIFICATE-----
  private_key: |
     -----BEGIN RSA PRIVATE KEY-----
     MIIG4wIBAAKCAYEAnKNJWuTJJJa5pW6P8/RmJw6SSaSQn4wfsSNw4s0AhAQ3FVVo
     irRK61TpqO0Msb5veopF7JW8pjpOgWwLpRFen6N69gbDQTY+t3fpz38o5uMHvmuL
     EMosMHnzvpqWJ6rXKghiDNtxs3LP9WZBL50D/tU/lGUEFerpDjrrFkfiWP2AWxoX
     Z1o+2RQ46NW6koQBx9vV6FiIp//R/xc24yMmB3wW6vXjYgxhDocEXG+34oIExB0Z
     N9sCKEPg3thXDh93dOXiFwuWvPwcO8qG0pKZeU61IAkENCVGeCC7NzI3WZQuC6kh
     0oszJtwv1jT/pi056L49wD9yyv1Sh0Ca2UK6vkbHglutOTtoM1Zj8t2tJnALjXRt
     m0bbZJtX6IcwITBI/vX1CsC2I+M5Q8FOQOj25PAdH/IXeunpWsHl/r+v9hCcVWaG
     GkBcvJm5A1gslz1Lmyil2lI/xA6f2Bbt+M0B6MzwwPOizrl2BSLuMRmnIoK1b5Ky
     sId9Zpdo7LbHCF7xAgMBAAECggGAPunq5cIs9DBCAqtk0HSirx9QLJoXqK2scQau
     KbpzcZML2NrEMan2yY0CiOIljiLSPeLZ8Qu3iQC0VZFjH/rZCb+s/LJ8rG2wRRq5
     46jMcehQTPB/G9BIbXQeLbmDhA0/fNd/InDlu1DrLELU/d3QJAPdFKp6OJ9w2lFZ
     6UoYJOw1KOJS8iUyRxizPvnRhVXWLUMkKL2erfO3kgDt/883UBxMTDVVDiWwuhgK
     7WHF9wmIBok1ftTNigSxhnBYjwid3o5cjMzx2Mqno/rxgSQymwYyfKox6ZeTEphM
     E+60PLbTgqCa1hIDe1DMzBgyNBD7iVj0FFwJHGhypsicXw1vzjTffceUuGt/hpDq
     KkkIQo0kv7R93aw+SB/JTU0IgBBI2TDZPp3ohRr2loMTCD0mlyPaz4+VVmVdd2at
     2dFGJmgaENeWio59Sg0SYKRoH319YeKjoVbE9CgWP1KYvVxhEizM1P9ozvliB13g
     lRTN0pJdN84O2/r9VJdrrun74DXRAoHBAMhl4FowRRNRRD13IYeFnRugJLBNrJ9o
     wcWxfUjgely2QMMYw0Lz4pLgiCiLxxJUcKO8hoAPt918ZagkjbOAUruKQof4mFqc
     4jknZKwbLoE6EQ2BHN9+2rD80AgB+VioclGBczBlkkooK1y+4Hm9PrmPQwjP7WIl
     xPkqB7MSVoYfZdVjw4km4QPMUjTNMJd0wxgdj+mYSBOfv5BoTt+3NK3EgdLZYorh
     aR5Eep4/kuJKcnkddAds6F7Dl2wYARfxnQKBwQDIGSkLw2Xp2YVo0n3KW7cAsK3q
     UCJWPJW29oPJKTEQtzfGbZjHqLo7HDRgNWEwHxW1HZgd7EfJAjuWDODaFCYsc5UW
     K+8bKsNh5mZw2V0HZ1TocmQJZenX8VZ9rbPXKNyf9ZPhEyHgSmOn4DqwEkKY16W5
     oVf4qm3+m3vU3Iv2p7bEnd2cjkHDaz1XPA5LI5VEk8euR3Brk8ychIoSfX+s5f7v
     YknZuB9Bh4lg1Km8PsKYrIRhkNRYuaUS5vdmfGUCgcAXOuAH9GJ9e8UqTt3/JLjy
     k9zM5yQkknMr5Ig+Y28rwiC9vOgdocHY/tgpwxI/iLRJ9resrqXEsf/ivuICNdTh
     UoSl2GZo0pjSwUNFRB1e84k4hIgBTGYzcAr5cqkh4tzln9jnek678+4a4TGKSyqz
     Pe0qX1gIMZKkw3+C/ZQ0Ff2q/9aR1oTs+Mlqv4JrfCiFah/dlz57r9/38G98NXOQ
     1R+rfnGS4dBaptuD7qCrRLACZCyoE7LYEVpDOIEf8m0CgcEAufGPkAvbF814SOlZ
     1YMW80A7zUL8NZEFO0mnO3bYzoTEAtPzpo4nySgzj7frAZHRVUYUBrJ8HtHBV3XO
     OTmCI8qgn0LiZid9+urlBTcoWOnwIDW0unsHLBFr40xYk7e4Fbla20wxLcFTDDy1
     rMq7Mlcq/O5u1nhh0LjiAPOV6Pb/Q4TD3Gjhudxc20TGr5J4coq1g0GFuaJWAJi1
     yervi1cLaZ63q+eKvBVcVywoMvNLWB7wwc2ZVn3lZURWYNl1AoHALvPK7UXmzUhj
     ScS1ROgTnWXWC92RK2H5MRPYUNTa6/GZ+aqX4wy0YiJEMcD1qxm913loOYRO9KuC
     /kO7EfADfT87ZuohWearnd2sJwBzkhXfxUYr8S4SwohIy/q5hSJ4QGLCZLDH01fx
     OFS73dE8tdh4XqMUT2/7dA2FOjFRbnmN7EFJAEnWVXLwDv6aB8lelVJ+Lwu4tHeK
     T9kcPluq2ib2Q6zHd5AIWBWhKb/ZDG3LV7xdx0rK2GRFucOPK20U
     -----END RSA PRIVATE KEY-----
